name: ipray
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  assets: 
    - assets/images/login.png
    - assets/icons/google.svg
    - assets/icons/time.svg
    - assets/icons/city.svg

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/poppins/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/poppins/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/poppins/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        weight: 700
          